[build]
  Command = "yarn build"
  Functions = "lambda"
  Publish = "build"

[[redirects]]
  from = "https://romainguilloteau.netlify.com/*"
  to = "https://www.romainguilloteau.com/:splat"

[[redirects]]
  from = "http://romainguilloteau.netlify.com/*"
  to = "https://www.romainguilloteau.com/:splat"
