[build]
  Command = "yarn build"
  Functions = "lambda"
  Publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://romainguilloteau.netlify.com/*"
  to = "https://www.romainguilloteau.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://romainguilloteau.netlify.com/*"
  to = "https://www.romainguilloteau.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://romainguilloteau.com/*"
  to = "https://www.romainguilloteau.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://romainguilloteau.fr/*"
  to = "https://www.romainguilloteau.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://rubyistdotjs.dev/*"
  to = "https://www.romainguilloteau.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://rubyistdotjs.com/*"
  to = "https://www.romainguilloteau.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://rubyistdotjs.fr/*"
  to = "https://www.romainguilloteau.dev/:splat"
  status = 301
  force = true
